datasource:
  url: https://jsonplaceholder.typicode.com/
logging:
  level:
    root: INFO
    com:
      github:
        madhawas1:
          postservice: DEBUG
management:
  endpoints:
    web:
      base-path: /api
server:
  port: 8081
  servlet:
    context-path: /api
spring:
  output:
    ansi:
      enabled: always
